version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    restart: unless-stopped
    depends_on:
      - migrate
      - redis
      - database
      - rabbitmq
    networks:
      - backend
      - rabbitmq_go_net

  redis:
    image: redis:6.2-alpine
    restart: unless-stopped
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - redis:/data
    networks:
      - backend

  database:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - ./db/sql:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=relationer
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_go_net
  

volumes:
  redis:
    driver: local
  database:
    driver: local

networks:
  rabbitmq_go_net:
    driver: bridge
  backend:
